file-root: "."

ocr:
  file-root: "models"
  keys-path: "ppocr_keys_v5.txt"
  det:
    model-path: "PP-OCRv5_mobile_det.bin"
    param-path: "PP-OCRv5_mobile_det.param"
  rec:
    model-path: "PP-OCRv5_mobile_rec.bin"
    param-path: "PP-OCRv5_mobile_rec.param"


refresh: on
refresh-interval: 100ms

dictionary-path: "dictionaries/cedict_ts.u8"

style: ~
width: 100
height: 100

anki:
  card-type: "Chinese Card Cloze"
  deck-name: "中文::看句子练习句子"
  card-tags:
    - "iwra"
  api-key: ~

  idle-timeout: 0ms

  fields:
    sentence: ""
    hanyu: ""
    pinyin: ""
    definition (word): ""
    definition (sentence): ""

