# if model_root is not supplied, defaults to working directory
model_root: "models"

# if only 1 is supplied, assumes both have same name
# if no file extension is supplied, assumes model is .bin, param is .param
det:
  model: "PP-OCRv5_mobile_det"
  param: "PP-OCRv5_mobile_det.param"

# model is either model or bin
# param is either param or params
rec:
  bin: "PP-OCRv5_mobile_rec.bin"
  params: "PP-OCRv5_mobile_rec"

key: "ppocr_keys_v5.txt"

refresh: on
refresh_interval: 100ms

html_template: "html_template.html"
dictionary: "dictionaries/hanyingcidian(disanban)"