file-root: "."

ocr:
  keys-path: "ppocr_keys_v5.txt"
  det:
    model-path: "PP-OCRv5_mobile_det"
    param-path: "PP-OCRv5_mobile_det.param"
  rec:
    model-path: "PP-OCRv5_mobile_rec.bin"
    param-path: "PP-OCRv5_mobile_rec"


refresh: on
refresh-interval: 100ms

html-template-path: "html_template.html"
dictionary-path: "dictionaries/cedict_ts.u8"

anki:
  card-type: "Chinese Card Cloze"
  deck-name: "中文::看句子练习句子"
